### PR TITLE
Fix #2

### LINKED ISSUE #2: undefined method `party' for #<Highrise::Deal:0x007fb67c834f98> (NoMethodError)
At https://github.com/railsware/highrise_assist/blob/master/lib/highrise_assist/command/export.rb#L167

```
# Deal: Found 434 items
~/.rvm/gems/ruby-1.9.3-p392/gems/activeresource-3.2.14/lib/active_resource/base.rb:1470:in `method_missing': undefined method `party' for #<Highrise::Deal:0x007fb67c834f98> (NoMethodError)
    from ~/.rvm/gems/ruby-1.9.3-p392/gems/highrise_assist-0.0.3/lib/highrise_assist/command/export.rb:167:in `casedeal_parties'
    from ~/.rvm/gems/ruby-1.9.3-p392/gems/highrise_assist-0.0.3/lib/highrise_assist/command/export.rb:148:in `block in filter_casedeal_collection!'
    from ~/.rvm/gems/ruby-1.9.3-p392/gems/highrise_assist-0.0.3/lib/highrise_assist/command/export.rb:147:in `reject!'
    from ~/.rvm/gems/ruby-1.9.3-p392/gems/highrise_assist-0.0.3/lib/highrise_assist/command/export.rb:147:in `filter_casedeal_collection!'
    from ~/.rvm/gems/ruby-1.9.3-p392/gems/highrise_assist-0.0.3/lib/highrise_assist/command/export.rb:41:in `block in run'
    from ~/.rvm/gems/ruby-1.9.3-p392/gems/highrise_assist-0.0.3/lib/highrise_assist/command/export.rb:38:in `each'
    from ~/.rvm/gems/ruby-1.9.3-p392/gems/highrise_assist-0.0.3/lib/highrise_assist/command/export.rb:38:in `run'
    from ~/.rvm/gems/ruby-1.9.3-p392/gems/highrise_assist-0.0.3/lib/highrise_assist/command.rb:13:in `run'
    from ~/.rvm/gems/ruby-1.9.3-p392/gems/highrise_assist-0.0.3/lib/highrise_assist/runner.rb:59:in `run!'
    from ~/.rvm/gems/ruby-1.9.3-p392/gems/highrise_assist-0.0.3/lib/highrise_assist/runner.rb:10:in `run'
    from ~/.rvm/gems/ruby-1.9.3-p392/gems/highrise_assist-0.0.3/bin/highrise_assist:5:in `<top (required)>'
    from ~/.rvm/gems/ruby-1.9.3-p392/bin/highrise_assist:19:in `load'
    from ~/.rvm/gems/ruby-1.9.3-p392/bin/highrise_assist:19:in `<main>'
    from ~/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
    from ~/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
```

### PR DESCRIPTION
**Pull request by heaven**
- Check if `Highrise::Deal` instance responds to party before use it
- Use `:force => true` when creating symlinks (to avoid file already exists error)

### CODE REVIEW

**Comment by heaven** [comment]
Hi, any progress with this? Should I forward this issue to highrise?

**Comment by ayanko** [comment]
@heaven 

This gem was updates 2 years ago and IFAIK Deal should 
- belongs to one party  
- have many parties

But looks like there are some changes. There is official highrise documentation:
https://github.com/basecamp/highrise-api/blob/master/sections/deals.md

And it says that there are
- Deal#party (The `party-id` field identifies the party that the deal is about, or for)
- Deal#responsible_party (The `responsible-party-id` field identifies which user is responsible for this deal)

But it's not clear which field  is required.

Should we change that part code to:

``` ruby
parties.push(casedeal.party) if casedeal.respond_to?(:party)
parties.push(casedeal.responsible_party) if casedeal.respond_to?(:responsible_party)
```

What do you think?
Can you investigate requirements for Deal#party and Deal#responsible_party?
Currently I don't have any highrise account so I can't even test it.

**Comment by heaven** [comment]
Sure, no worries, I'll check this (will try today, otherwise tomorrow morning).

**Comment by heaven** [comment]
I've found the next:

```
(byebug) casedeal.party
NoMethodError Exception: undefined method `party' for #<Highrise::Deal:0x007fbc5e34bfa8>
nil
(byebug) casedeal.responsible_party
NoMethodError Exception: undefined method `responsible_party' for #<Highrise::Deal:0x007fbc5e34bfa8>
nil
```

But the `responsible_party_id` is set (and the `party_id` is `nil`). So I think my fix should be fine or we have to submit an issue to highrise. Or do both :)

**Comment by ayanko** [comment]
Ok. Released v0.0.4

**Comment by heaven** [comment]
Many thanks :+1:

**Pull request merged**
